language: java
services: docker
sudo: true
before_install:
  - wget "https://api.adoptopenjdk.net/v3/binary/latest/14/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk" -O ${TRAVIS_HOME}/OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz
  - tar xvzf ${TRAVIS_HOME}/OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz
  - export JAVA_HOME=jdk-14.0.2+12
  - export PATH=$JAVA_HOME/bin:$PATH
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - az --version
  - docker build -t url-shortner .
  - docker login ${ACR_REGISTRY} -u ${ACR_REGISTRY_USER} -p ${ACR_REGISTRY_PWD}
  - docker tag url-shortner ${ACR_REGISTRY}/sample/url-shortner
  - docker push ${ACR_REGISTRY}/sample/url-shortner
  - az login --tenant ${TENANT_ID}
  - az aks get-credentials --resource-group ${AZ_RES_GRP} --name ${AZ_CLSTR} --file kube/url-kube.yml
