language: java
sudo: true
before_install:
  - wget https://api.adoptopenjdk.net/v3/binary/latest/14/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk?project=jdk
  - tar xvzf OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz
  - export JAVA_HOME=$PWD/jdk-14.0.2+12
  - export PATH=$JAVA_HOME/bin:$PATH
after_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version