apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
        - name: url-shortner
          image: sivacontainerregistry.azurecr.io/sample/url-shortner:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
